### ISSUE TITLE
Debug email sending in staging and production

### ISSUE THREAD

**Issue by simon-wacker** [ise621/metabase#61]
Why does it not work? How exactly does the ISE mail transfer agent work? Maybe https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-configure-network-tracing and https://blogs.msmvps.com/bsonnino/2018/10/20/debugging-emails-sent-with-c/ are helpful for debugging the communication.

**Comment by christoph-maurer** [comment]
Answer from Thomas Graf at 27.5.21:

1. There are two options. a) Create your own Mail Transfer Agent (MTA) and use localhost:25 . b) Use the central Fraunhofer MTA. You find the four URLs/IP addresses [here](https://inside.fraunhofer.de/CC-Daten/index.php/Mail-Routing_zum_und_vom_Institut). The first one is mail-mtaKA26.fraunhofer.de / 153.96.1.26 .
2. Thomas thinks that Port 25 should be used.
3. We don't need to authenticate ourselves. The IP address of the metabase is used for authentification.
4. We don't need to specify an email address for sending emails, but we are free to specify any email address. We should use a library to communicate with the SMTP endpoint. This library should be able to specify the email address.
5. Yes, see answer 4.
6. Yes, we simply need to open a ticket. Then the ISE IT creates the email address and the forwarding.

**Comment by simon-wacker** [comment]
In development and staging emails are intercepted by `smtp4dev`, which works since https://github.com/ise621/metabase/commit/30828eeb0cba7cd272ab367d6e7efdaf6f0b9914 As of https://github.com/ise621/metabase/commit/6dd8158b97025f837a7213a59112c77b1ef2639a, in staging, emails are relayed to `mta.mx.fraunhofer.de` when they are whitelisted in the copy of https://github.com/ise621/metabase/blob/30828eeb0cba7cd272ab367d6e7efdaf6f0b9914/.env.staging.sample#L15, and in production, emails are sent directly to `mta.mx.fraunhofer.de`. Both relaying and sending directly does not work yet. Why?

**Comment by simon-wacker** [comment]
I added a logging diagnostic event listener to the GraphQL pipeline in https://github.com/ise621/metabase/commit/6f7a0fa319c8f435c5ff34846822c4257b48a4fc so that exceptions are logged.

**Comment by simon-wacker** [comment]
The domain `mta.mx.fraunhofer.de` cannot be resolved. I thus used `mail-mtaKA26.fraunhofer.de` instead. The list of all options is

* `mail-mtaKA26.fraunhofer.de`
* `mail-mtaKA28.fraunhofer.de`
* `mail-mtaS26.fraunhofer.de`
* `mail-mtaDD25.fraunhofer.de`

which I took from https://inside.fraunhofer.de/CC-Daten/index.php/Mail-Routing_zum_und_vom_Institut Ideally, we would try all those in turn.
