### ISSUE TITLE
Text for the front end

### ISSUE THREAD

**Issue by christoph-maurer** [ise621/metabase#89]
We need text on buildingenvelopedata.org to explain the website to beginners.

**Comment by christoph-maurer** [comment]
Text for the tab `Home` [WIP]

Buildingenvelopedata.org offers you access to a network of databases. It contains detailed optical data for thousands of building envelope components. [to be continued]

**Comment by christoph-maurer** [comment]
Text for the tab 'Institutions' [WIP]

Institutions can manufacture [components](https://www.buildingenvelopedata.org/components), operate [databases](https://www.buildingenvelopedata.org/databases) and create [data formats](https://www.buildingenvelopedata.org/data-formats) and [methods](https://www.buildingenvelopedata.org/methods).

Table

The [GraphQL endpoint](https://www.buildingenvelopedata.org/graphql) offers all information about the institutions.

**Comment by christoph-maurer** [comment]
Text for the tab 'Data Formats' [WIP]

[Data](https://www.buildingenvelopedata.org/data) is shared as a resource. Each resource has one of the following data formats:

Table

The [GraphQL endpoint](https://www.buildingenvelopedata.org/graphql) offers all information about the data formats.

**Comment by christoph-maurer** [comment]
Text for the tab 'Methods' [WIP]

[Data](https://www.buildingenvelopedata.org/data) is created by applying a method. Methods can be defined for example by a standard.

Table

The [GraphQL endpoint](https://www.buildingenvelopedata.org/graphql) offers all information about the methods.

**Comment by christoph-maurer** [comment]
Text for the tab 'Components' [WIP]

The building envelope components for which [data](https://www.buildingenvelopedata.org/data) is available are presented here. 

Table

The [GraphQL endpoint](https://www.buildingenvelopedata.org/graphql) offers all information about the components.

**Comment by christoph-maurer** [comment]
Text for the tab 'Databases' [WIP]

The following databases are connected with buildingenvelopedata.org and offer [data](https://www.buildingenvelopedata.org/data) about [components](https://www.buildingenvelopedata.org/components).

Table

The [GraphQL endpoint](https://www.buildingenvelopedata.org/graphql) offers all information about the databases.

**Comment by christoph-maurer** [comment]
Text for the tab 'Data' [WIP]

The network of [databases](https://www.buildingenvelopedata.org/databases) can be queried here for data about building envelope [components](https://www.buildingenvelopedata.org/components).

Table

The [GraphQL endpoint](https://www.buildingenvelopedata.org/graphql) offers the most powerful way of querying the databases.

**Comment by christoph-maurer** [comment]
Text for the tab 'Register' [WIP]

No account is needed to query the [data](https://www.buildingenvelopedata.org/data) for free! If you work for example for a manufacturer of building envelope components and want to add data, then you can apply here for a paid account.###

Table

The [GraphQL endpoint](https://www.buildingenvelopedata.org/graphql) offers the most powerful way of querying the databases.

**Comment by christoph-maurer** [comment]
Text for the tab 'Login' [WIP]

You don't need to login to query the [data](https://www.buildingenvelopedata.org/data) for free! 

If you want to change data about [institutions](https://www.buildingenvelopedata.org/institutions), [data formats](https://www.buildingenvelopedata.org/data-formats), [methods](https://www.buildingenvelopedata.org/methods), [components](https://www.buildingenvelopedata.org/components) or [databases](https://www.buildingenvelopedata.org/databases), please login here or [register](https://www.buildingenvelopedata.org/register).

Table

The [GraphQL endpoint](https://www.buildingenvelopedata.org/graphql) can be used without an account for queries. For mutations, please login or [register](https://www.buildingenvelopedata.org/register).

**Comment by christoph-maurer** [comment]
Text for the tab 'Users' [WIP]

A user is usually affiliated to an [institution](https://www.buildingenvelopedata.org/institutions) and can receive the permission for example to add [components](https://www.buildingenvelopedata.org/components) manufactured by this institution. 

Table

The [GraphQL endpoint](https://www.buildingenvelopedata.org/graphql) can be used without an account for queries. For mutations, please login or [register](https://www.buildingenvelopedata.org/register).

**Comment by christoph-maurer** [comment]
@simon-wacker I've developed drafts for the text of the website. What do you think about it?

**Comment by simon-wacker** [comment]
I like the descriptions --- concise and to the point. Instead of `The backend of the metabase can be used by its GraphQL endpoint.` in `Home` I would write `The metabase can be queried through its GraphQL endpoint.`

Side note: We probably need a page or at least some sentences on the pricing mentioned in `Register`.

**Comment by christoph-maurer** [comment]
I updated the descriptions in `Home` and `Register`.

**Comment by simon-wacker** [comment]
No, Joerg can't program typescript.
