### ISSUE TITLE
Fix column `Abbreviation` in frontend tab `Institutions`

### ISSUE THREAD

**Issue by christoph-maurer** [ise621/metabase#97]
I think the abbreviation of `Fraunhofer ISE` is `ISE`. The column `Abbreviation` seems to duplicate the column `Description`.
![image](https://user-images.githubusercontent.com/33456252/130450164-41685df7-6322-48d6-badf-83235535d518.png)

**Comment by simon-wacker** [comment]
Already fixed in development (I'm reluctant to search for the corresponding commit though).
