### ISSUE TITLE
Add reference to github to the frontend

### ISSUE THREAD

**Issue by christoph-maurer** [ise621/metabase#98]
I propose to add an additional paragraph to the tab `Home` of buildingenvelopedata.org after the currently last paragraph

> 
The metabase can be queried through its GraphQL endpoint. This is the most powerful way to query all databases. It is well suited to be used by software. The tabs of this website can offer only a part of the functions of the GraphQL endpoint.

I propose the following text for the additional paragraph:

With [BED-JSON](https://www.buildingenvelopedata.org/data-formats/9ca9e8f5-94bf-4fdd-81e3-31a58d7ca708), [buildingenvelopedata.org](https://www.buildingenvelopedata.org/) offers a general format for optical, calorimetric and photovoltaic data sets. It is defined by the JSON Schemas of the [buildingenvelopedata.org API specification](https://github.com/ise621/building-envelope-data). Other [data formats](https://www.buildingenvelopedata.org/data-formats) are as well available. The source code of the metabase is available at [GitHub](https://github.com/ise621/metabase).

I addition, a figure at the right side of the text may be helpful. I add a proposal in three file formats.
[buildingenvelopedataOrgOverview_d01.zip](https://github.com/ise621/metabase/files/7033092/buildingenvelopedataOrgOverview_d01.zip)

**Comment by simon-wacker** [comment]
Resolved by https://github.com/ise621/metabase/commit/269055b507a4108aa23b204184c2a8ec7bd20bd3
